function [plt,B] = makePITTrackButtons
% to create buttons & fields on figure

plt.y = 800;
plt.x = 1200;
plt.yi = 20;
plt.xi = 20;
plt.col = [205 205 205]/255;

plt.id = figure;

set(plt.id,'Units','pixels');
set(plt.id,'Position',[plt.xi plt.yi plt.x plt.y]);
set(plt.id,'PaperPositionMode','auto');

% set colors for figure
backcol = [255 245 170]/255; % used on level 1 boxes
backcol2 = [210 255 255]/255; % used on axes boxes

ux = 25; % grid size
yni = 25; % vertical location for first button on panels
yb = ux; % standard button height
xb = 6*ux; % standard button width
xni = 0; % button number (first column is 0)

xib = ux;
Fsize = 10;

yp = plt.y-100;
xp = plt.x;

%%%%% Title block
figtitle = uicontrol('Style','text',...
            'Units','pixels',...
            'FontSize',Fsize+8,...
            'FontName','Calibri',...
            'ForegroundColor','b',...
            'Position',[ux*2,30.25*ux,xb*2,yb*1.25],...
            'String','PITTrack');
figtitle = uicontrol('Style','text',...
            'Units','pixels',...
            'FontSize',Fsize+4,...
            'FontName','Calibri',...
            'ForegroundColor','b',...
            'Position',[ux*2,28.5*ux,xb*2,yb*1.75],...
            'String','A software for RFID sediment tracer visualization and analysis (beta)');

% create panels
pan.name = {'Site Properties';'Add Tracers';'Add Survey';'Visualize Results';'Analyze Results'};

npantot = length(pan.name);

for npan = 1:npantot
    % pushbutton
    B.panelbutton(npan) = uicontrol(plt.id,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[16*ux+xb*(npan-1),29*ux,xb,yb*2],...
            'FontSize',Fsize+2,...
            'BackgroundColor','w',...
            'ForegroundColor','k',...
            'String',pan.name{npan});
    
    % ui panel listing all filter array options and parameters
    B.panel(npan) = uipanel(plt.id,'Title',pan.name{npan},...
        'Units','pixels',...
        'FontSize',Fsize,...
        'BackgroundColor',backcol,...
        'Position',[0 0 xp yp]);
    if npan ~=1
        set(B.panel(npan),'Visible','off');
    end
end

%% Site Properties panel
pan.active = B.panel(1);

yn = yni ;
xn = xni;
B.seldefdir = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Default Directory');
xn = xn+1;
B.defdir = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','none');

%
yn =  yn-1;
xn = xni;
B.selsitename = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Site Name');
xn = xn+1;
B.sitename = uicontrol(pan.active,'Style','edit',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','on',...
            'String','name');
%
yn =  yn-1;
xn = xni;
B.selthalwegfile = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Thalweg File');
xn = xn+1;
B.C.thalwegfile = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','none');
yn =  yn-1;
xn = xni;
B.sellabfile = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Lab CSV file');
xn = xn+1;
B.C.labfile = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','none');
% add reach break button
yn = yn-1;
xn = xni;
B.SiteReachesAdd = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Add Reach Break');
xn = xn+1;
B.SiteReachesReset = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','on',...
            'String','Reset Reach Breaks');

        
% background image
yn =  yn-1;
xn = xni;
B.selbackground = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Background Image');
xn = xn+1;
B.C.background = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','none');

        %       
% save
yn =  yn-2;
xn = xni;
B.saveC = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Save');

        % 
% display plan view
yn = yni ;
xn = 5;

axexi = xib+xb*xn+5;
axewidth = xb*2.5;
axeheight = axewidth;
axeyi = yn*yb-axeheight;

% create axes
B.mainplanaxes = axes('Units','pixels',...
    'Parent',pan.active,...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Easting (m)')
ylabel('Northing (m)')

yn = yn-1 ;
        

%% Add Tracers panel
pan.active = B.panel(2);

% add tags button
yn = yni ;
xn = xni;
B.seladdtags = uicontrol(pan.active,'Style','radiobutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Add Tags');
% choose either to do it with a list or manually
xn = xn+1;
B.seladdtagsmethod = uicontrol(pan.active,'Style','popupmenu',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*0.75,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','off',...
            'String','*.csv file|manual entry');
% ui panel for adding tags
yn =  yn-3;
xn = xni;
B.addtagsfilepanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*3]);
smpan.xi = 0;
smpan.num =  1;
smpan.col = 1;
smxp = xb;
smyp = yb;
B.selplacementfile = uicontrol(B.addtagsfilepanel,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Placement CSV file');
smpan.col = 2;
B.placementfile = uicontrol(B.addtagsfilepanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp,smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','filename');


% add tags manually panel
B.addtagsmanualpanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*3]);

% Go button (add or remove tags)
yn =  yn-1;
xn = xn+1;
B.goadd = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');       
% remove tags button
yn = yn-6;
xn = xni;
B.selremtags = uicontrol(pan.active,'Style','radiobutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Remove Tags');
% choose either to do it with a list or manually
xn = xn+1;
B.selremtagsmethod = uicontrol(pan.active,'Style','popupmenu',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*0.75,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','off',...
            'String','*.csv file|manual entry');
% ui panel for adding tags
yn =  yn-3;
xn = xni;
B.remtagscsvpanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*3]);
smpan.xi = 0;
smpan.num =  1;
smpan.col = 1;
smxp = xb;
smyp = yb;
B.selcsvremovalfile = uicontrol(B.remtagscsvpanel,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Removal CSV file');
smpan.col = 2;
B.csvremovalfile = uicontrol(B.remtagscsvpanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp,smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','filename');

% Go button remove tags
yn =  yn-1;
xn = xn+1;
B.goremove = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');
        
% placement dates selection listbox             
yn =  yn-3;
xn = xni;
% select placement dates
B.placementdatestext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*2],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Select tracer placement dates for analysis');
xn = xn+1;
yn =  yn-2;
B.C.placementdates = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*3],...
            'FontSize',Fsize,...
            'Max',5,...
            'BackgroundColor','w');
% choose either to compare or combine the placement data
yn =  yn-1;
B.selplacementseemethod = uicontrol(pan.active,'Style','popupmenu',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*0.75,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','combine|compare|single');% Go button (add or remove tags)
yn =  yn-1;
B.goseeplacement = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');
        
% reset placement dates button             
yn =  yn-1;
xn = xni;
% select placement dates
B.resetplacementdatestext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*2],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Re-analyze placement dates');
xn = xn+1;
B.resetplacementdates = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Re-analyze');
       
        
        
% placement data
yn = yni ;
xn = 3;
B.surveydatatext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'String','Tag Placement Data');
yn =  yn-4;
B.surveydatatable = uitable(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'Position',[xib+xb*xn,yn*yb,xb*4,yb*4],...
            'ColumnWidth',{100 60},...
            'ColumnName',{'Date','n_t'});

% create axis to display
yn =  yn-5;

axemarg = 60;
axexi = xib+xb*xn+axemarg;
axewidth = xb*2-axemarg;
axeheight = axewidth;
axeyi = yn*yb-axeheight+axemarg;

% multiple axes
B.axesplacementhist = axes('Units','pixels',...
    'Parent',pan.active,...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Particle Size \phi')
ylabel('Frequency')

xn = xn+2;
axexi = xib+xb*xn+axemarg;
axewidth = xb*2-axemarg;
axeheight = axewidth;
axeyi = yn*yb-axeheight+axemarg;

% multiple axes
B.axesplacementcumulative = axes('Units','pixels',...
    'Parent',pan.active,...
    'YLim',[0 1],...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Particle Size \phi')
ylabel('% smaller than')

   
%% Add Surveys panel
pan.active = B.panel(3);

% add tags button
yn = yni ;
xn = xni;
B.seladdsurvey = uicontrol(pan.active,'Style','radiobutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Add Survey');
% choose either to do it with a list or manually
xn = xn+1;
B.seladdsurveymethod = uicontrol(pan.active,'Style','popupmenu',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*0.75,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','off',...
            'String','*.csv file|manual entry');
% ui panel for adding tags
yn =  yn-3;
xn = xni;
B.addsurveyfilepanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*3]);
smpan.xi = 0;
smpan.num =  1;
smpan.col = 1;
smxp = xb;
smyp = yb;
B.selsurveyfile = uicontrol(B.addsurveyfilepanel,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Survey CSV file');
smpan.col = 2;
B.surveyfile = uicontrol(B.addsurveyfilepanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp,smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','filename');
smpan.num =  smpan.num-1;
smpan.col = 1;
B.surveydate = uicontrol(B.addsurveyfilepanel,'Style','edit',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','date');

        % Go button (add or remove tags)
yn =  yn-1;
xn = xn+1;
B.goaddsurvey = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');       

% survey dates selection listbox             
yn =  yn-3;
xn = xni;
% select survey dates
B.surveydatestext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*2],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Select tracer survey dates for analysis');
xn = xn+1;
yn =  yn-7;
B.C.surveydates = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*8],...
            'FontSize',Fsize,...
            'Max',100,...
            'BackgroundColor','w');
% choose either to compare or combine the survey data
yn =  yn-1;
B.selsurveyseemethod = uicontrol(pan.active,'Style','popupmenu',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*0.75,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','combine|compare|single');% Go button (add or remove tags)
yn =  yn-1;
B.goseesurvey = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');

% survey data
yn = yni ;
xn = 3;
B.surveydatatext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'String','Tag Survey Data');
yn =  yn-4;
B.surveydatatable = uitable(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'Position',[xib+xb*xn,yn*yb,xb*4,yb*4],...
            'ColumnWidth',{100 60},...
            'ColumnName',{'Date','n_t'});

% create axis to display
yn =  yn-5;

axemarg = 60;
axexi = xib+xb*xn+axemarg;
axewidth = xb*2-axemarg;
axeheight = axewidth;
axeyi = yn*yb-axeheight+axemarg;

% multiple axes
B.axessurveyhist = axes('Units','pixels',...
    'Parent',pan.active,...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Particle Size \phi')
ylabel('Frequency')

xn = xn+2;
axexi = xib+xb*xn+axemarg;
axewidth = xb*2-axemarg;
axeheight = axewidth;
axeyi = yn*yb-axeheight+axemarg;

% multiple axes
B.axessurveycumulative = axes('Units','pixels',...
    'Parent',pan.active,...
    'YLim',[0 1],...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Particle Size \phi')
ylabel('% smaller than')

%% Visualize Results panel
pan.active = B.panel(4);

yn = yni;
xn = xni;
B.initializeViz = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','on',...
            'String','Initialize Visualization');

% placement dates block
% listbox
yn = yn-2;
% select placement dates
B.Vizplacementtext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Tracer Placement Dates');
yn = yn-2;
B.Vizplacementdates = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*2],...
            'FontSize',Fsize,...
            'Max',5,...
            'BackgroundColor','w');

% % finished button
yn = yn-1;
% Clear placement dates
B.VizPlacementClear = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*0.5,yn*yb,xb*0.5,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Clear');
% placement dates data
yn = yni-5;
xn = 1;
B.Vizplacementdatatable = uitable(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*4],...
            'ColumnWidth',{100 60},...
            'ColumnName',{'Date','n_t'});



% survey dates block
% listbox
yn = yn-2;
xn = xni;
% select placement dates
B.Vizsurveytext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Tracer Survey Dates');
yn = yn-2;
B.Vizsurveydates = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*2],...
            'FontSize',Fsize,...
            'Max',5,...
            'BackgroundColor','w');

% % finished button
yn = yn-1;
% clear survey dates
B.VizSurveyClear = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*0.5,yn*yb,xb*0.5,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Clear');

% survey dates data
yn = yn;
xn = 1;
B.Vizsurveydatatable = uitable(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb*4],...
            'ColumnWidth',{100 60},...
            'ColumnName',{'Date','n_t'});


% sizes block
yn =  yn-2;
xn = xni;
% select placement dates
B.Vizsizestext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Tracer Size Classes');
xn = xn+1;
B.Vizselsizeall = uicontrol(pan.active,...
            'Style','radiobutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*.75],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Value',0,...
            'String','All Sizes');

partsizes = [3:0.5:9];
nztot = length(partsizes);
sizestring = cell(1,nztot-1);
for nz = 1:nztot-1
    sizestring(nz) = cellstr([num2str(partsizes(nz)),' - ',num2str(partsizes(nz+1))]);
end

yn = yn-3;
B.Vizselsize = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*3],...
            'FontSize',Fsize,...
            'Max',100,...
            'String',sizestring,...
            'BackgroundColor','w');
% reach block
yn = yn-2;
xn = xni;
% select reaches
B.VizReachestext = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Limit by Reach');
% select all reaches
xn = xn+1;
B.Vizselreachall = uicontrol(pan.active,...
            'Style','radiobutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*.75],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Value',0,...
            'String','All Reaches');
% % choose reaches
yn = yn-3;
B.VizReaches = uicontrol(pan.active,'Style','listbox',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb*3],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',100,...
            'Enable','on',...
            'String','');

% % show DEM
% background image
yn =  yn-1;
xn = xni;
B.VizDEM = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Select Background Image');
xn = xn+1;
B.C.VizDEMfile = uicontrol(pan.active,'Style','text',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb*2,yb],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'String','none');

        % % % finished button
yn = yn-2;
xn = xni;
B.VizShow = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Plot Selected Data');
        
% display plan view
yn = yni ;
xn = 3.5;

axexi = xib+xb*xn+5;
axewidth = xb*3.8;
axeheight = axewidth;
axeyi = yn*yb-axeheight;

% create axes
B.Vizplanaxes = axes('Units','pixels',...
    'Parent',pan.active,...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Easting (m)')
ylabel('Northing (m)')

yn =  4;
xn = 3;

axexi = xib+xb*xn+5;
axewidth = xb*4.5;
axeheight = axewidth/10;
axeyi = 40;

% % create axes
% B.longaxes = axes('Units','pixels',...
%     'Parent',pan.active,...
%     'Position',[axexi,axeyi,axewidth,axeheight]);
% xlabel('Particle Size \phi')
% ylabel('% smaller than')
% 
% axeheight = axewidth/20;
% axeyi = 115;
% 
% % create axes
% B.longbaraxes = axes('Units','pixels',...
%     'Parent',pan.active,...
%     'Position',[axexi,axeyi,axewidth,axeheight]);

%% Analyse Results panel

pan.active = B.panel(5);

yn = yni;
xn = xni;
B.initializeAna = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','on',...
            'String','Initialize Analysis');


% table of existing data
yn =  yn-4;
B.AnaSeriesData = uitable(pan.active,...
    'Units','pixels',...
    'FontSize',10,...
    'Position',[xib+xb*xn,yn*yb,xb*3,yb*4],...
    'ColumnWidth',{40 80 80 40 40 40 40 40 40 40},...
    'ColumnName',{'Series','Start Date','End Date','Reach','nt','nf1','nf2','ni','ninf','nind','nm','nl','LD50'});

% add data push button
yn =  yn-2;
B.AnaAddData = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Add Data Series');
        
% add data panel
yn =  yn-8;
xn = xni;
B.AnaAddDataPanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2.02,yb*8]);
smpan.xi = 0;
smpan.num =  6.6;
smxp = xb;
smyp = yb;
% name
smpan.col = 1;
B.AnaNametext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Name');
smpan.col = 1.5;
B.AnaName = uicontrol(B.AnaAddDataPanel,'Style','edit',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*1.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','on',...
            'String','');
% start & end dates
smpan.num =  smpan.num-1.1;
smpan.col = 1;
B.AnaStarttext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Start Date');
smpan.col = 2;
B.AnaEndtext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','End Date');

smpan.num =  smpan.num-1.3;
smpan.col = 1;
B.AnaStart = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp*1.5],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',1,...
            'Enable','on',...
            'String','');
smpan.col = 2;
B.AnaEnd = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp,smyp*1.5],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',1,...
            'Enable','on',...
            'String','');

% reach
smpan.num =  smpan.num-1.1;
smpan.col = 1;
B.AnaFromtext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.65,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','From rch brk');
smpan.col = 1.65;
B.AnaFrom = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.35,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',1,...
            'Enable','on',...
            'String','');
smpan.col = 2;
B.AnaTotext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.65,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','To rch brk.');
smpan.col = 2.65;
B.AnaTo = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.35,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',1,...
            'Enable','on',...
            'String','');
% Restrict by wave number
% reach
smpan.num =  smpan.num-1.1;
smpan.col = 1;
B.AnaWavetext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.65,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Wave number');
smpan.col = 1.65;
B.AnaWaveall = uicontrol(B.AnaAddDataPanel,...
            'Style','radiobutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.65,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Max',10,...
            'Value',0,...
            'String','All Waves');
smpan.col = 2.65;
B.AnaWaveList = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.35,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Max',1,...
            'Enable','on',...
            'String','');

% symbol
smpan.num =  smpan.num-1.1;
smpan.col = 1;
B.AnaSymboltext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.33,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Symbol');
smpan.col = 1.33;
B.AnaSymbol = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.33,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','on',...
            'Value',1',...
            'String','x|+|.|o|s|v|^|*|p');

% color
smpan.col = 1.66;
B.AnaColortext = uicontrol(B.AnaAddDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.34,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Color');
smpan.col = 2;
B.AnaColor = uicontrol(B.AnaAddDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.33,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','on',...
            'Value',1',...
            'String','k|b|r|g|c|m');

% filled
smpan.col = 2.5;
B.AnaFilled = uicontrol(B.AnaAddDataPanel,...
            'Style','radiobutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Value',0,...
            'String','Filled');
% go add pushbutton
smpan.num =  0;
smpan.col = 2.5;
B.AnaGoAdd = uicontrol(B.AnaAddDataPanel,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');
        
        
% remove data panel
% add data push button
yn =  yn+8;
xn = xni+1;
B.AnaRemData = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yn*yb,xb,yb],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'String','Remove Data Series');
        
% remove data panel
yn =  yn-8;
xn = xni;
B.AnaRemDataPanel = uipanel(pan.active,...
            'Units','pixels',...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'Visible','off',...
            'Position',[xib+xb*xn,yn*yb,xb*2.02,yb*8]);

 % name
smpan.col = 1;
smpan.num =  6.6;
B.AnaRemNametext = uicontrol(B.AnaRemDataPanel,'Style','text',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',backcol,...
            'String','Name');
smpan.num =  smpan.num-3.1;
B.AnaRemName = uicontrol(B.AnaRemDataPanel,'Style','listbox',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*1.5,smyp*3],...
            'FontSize',Fsize,...
            'BackgroundColor','w',...
            'Enable','on',...
            'String','');       
 % go rem pushbutton
smpan.num =  0;
smpan.col = 2.5;
B.AnaGoRem = uicontrol(B.AnaRemDataPanel,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[smpan.xi+smxp*(smpan.col-1),smpan.num*smyp,smxp*0.5,smyp],...
            'FontSize',Fsize,...
            'BackgroundColor',plt.col,...
            'Enable','off',...
            'String','Go');

%Figure panels
% create panels
panfig.name = {'Mobility';'Distance Histogram';'Normalized Distance';'Image'};

npanftot = length(panfig.name);
yn = yn-3 ;
xn = 1.5;
for npanf = 1:npanftot
    % pushbutton
    B.panfigbutton(npanf) = uicontrol(pan.active,'Style','pushbutton',...
            'Units','pixels',...
            'Position',[xib+xb*xn,yb*(yn-2.5*(npanf-1)),xb*1.5,yb*1.5],...
            'FontSize',Fsize+2,...
            'BackgroundColor','w',...
            'ForegroundColor','k',...
            'String',panfig.name{npanf});
    
    % ui panel listing all filter array options and parameters
    B.panfig(npanf) = uipanel(pan.active,'Title',panfig.name{npanf},...
        'Units','pixels',...
        'FontSize',Fsize,...
        'BackgroundColor',backcol,...
        'Position',[xib+xb*(xn+1.5) 0 xp-100 yp]);
    if npanf ~=1
        set(B.panfig(npanf),'Visible','off');
    end
end

        
        
% mobility curve

axexi = xb*0.5;
axeyi = axexi;
axewidth = xb*2.5;
axeheight = axewidth;

% create axes
B.AnaMobility = axes('Units','pixels',...
    'YLim',[0 1],...
    'YTick',0:.1:1,...
    'XLim',[4 9],...
    'XTick',4:0.5:9,...
    'NextPlot','add',...
    'Parent',B.panfig(1),...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('D (\phi)');
ylabel('p_m');

axe2 = axes('Units','pixels',...
    'Parent',B.panfig(1),...
    'Position',get(B.AnaMobility,'Position'),...
    'XAxisLocation','top',...
    'YAxisLocation','left',...
    'Color','none',...
    'XColor','k','YColor','k');
set(axe2,'YLim',[0 1]);
set(axe2,'YTick',[]);
set(axe2,'XLim',[4 9]);
set(axe2,'XTick',4:1:9);
set(axe2,'XTickLabel',2.^[4:1:9]);
xlabel('D (mm)');

% distance histogram

% normalized relative distance figure
axexi = xb*0.5;
axeyi = axexi;
axewidth = xb*3.8/2;
axeheight = axewidth*2;

% create axes
B.AnaNormPathLength = axes('Units','pixels',...
    'Yscale','log',...
    'YLim',[0.1 10],...
    'YGrid','on',...
    'Xscale','log',...
    'XLim',[0.5 5],...
    'XGrid','on',...
    'NextPlot','add',...
    'Parent',B.panfig(3),...
    'Position',[axexi,axeyi,axewidth,axeheight]);
ylabel('L'' / L_{D50}''')
xlabel('D / D_{50}')

% image

axexi = xib+xb*xn+5;
axewidth = xb*2.5;
axeheight = axewidth;
axeyi = axexi;

% create axes
B.Anaplanaxes = axes('Units','pixels',...
    'Parent',B.panfig(4),...
    'Position',[axexi,axeyi,axewidth,axeheight]);
xlabel('Easting (m)')
ylabel('Northing (m)')

end
%%%%%
